routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductoController;
use App\Http\Controllers\CarritoController;
use App\Http\Controllers\PedidoController;
use App\Http\Controllers\userController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Models\Pedido;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('products', ProductController::class);

Route::resource('productos', ProductoController::class);

Route::resource('perfils', ProductoController::class);



Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('/perfil', function () {
    return view('perfiles.perfil');
})->name('perfil');

Route::get('/carrito', [CarritoController::class, 'mostrarCarrito'])->name('carrito');

Route::get('/pagar', [CarritoController::class, 'pagar'])->name('pagar');

Route::post('/carrito/agregar', [CarritoController::class, 'agregarAlCarrito'])->name('agregarAlCarrito');

Route::get('/carrito/eliminar/{productoId}', [CarritoController::class, 'eliminarDelCarrito'])->name('eliminarDelCarrito');

Route::post('/carrito/remove/{index}', [CarritoController::class, 'remove'])->name('carrito.remove');

// routes/web.php

Route::get('/pedidos', function () {
    $pedidos = App\Models\Pedido::all(); // Obtén los pedidos desde el modelo Pedido (ajusta esto según tus necesidades)
    return view('pedido.pedidos', compact('pedidos'));
})->name('pedido.pedidos');





Route::get('/pedidos', [PedidoController::class, 'index'])->name('pedidos.index');

Route::post('/pedidos', [PedidoController::class, 'guardar'])->name('pedidos.guardar');



Route::resource('permission', App\Http\Controllers\permissionController::class);
Route::resource('roles', App\Http\Controllers\RoleController::class);

Route::get('/usuarios', [userController::class, 'index'])->name('usarios.index');

Route::post('/asignar-rol', [App\Http\Controllers\AsignarRolController::class, 'asignarRol'])->name('asignar_rol');

app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    protected $table = 'productos';

    protected $fillable = [
        'nombre',
        'precio',
       
    ];
}

app/Http/Controllers/ProductoController.php
<?php
namespace App\Http\Controllers;
use App\Models\Producto;
use Illuminate\Http\Request;
use Laravel\Ui\ControllersCommand;

class ProductoController extends ControllersCommand{
    public function index()
    {
        $productos = Producto::all();
        return view('productos.index', compact('productos'));

    }
    
    public function create()
    {
        return view('productos.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required',
            'precio' => 'required|numeric',
        ]);

        //dd($request);

        Producto::create($request->all());

   

       
        return redirect()->route('productos.index')->with('success', 'Producto creado exitosamente');
    }

    public function show(Producto $producto)
    {
        return view('productos.show', compact('producto'));
    }

    public function edit(Producto $producto)
    {
        return view('productos.edit', compact('producto'));
    }

    public function update(Request $request, Producto $producto)
    {
        $request->validate([
            'nombre' => 'required',
            'precio' => 'required|numeric',
            //'detalle'=> 'required',
        ]);

        $producto->update($request->all());
        return redirect()->route('productos.index')->with('success', 'Producto actualizado exitosamente');
    }

    public function destroy(Producto $producto)
    {
        $producto->delete();
        return redirect()->route('productos.index')->with('success', 'Producto eliminado exitosamente');
    }

    
}

resources/views/productos/create.blade.php
<!-- resources/views/productos/create.blade.php -->
@extends('layouts.app') 
<link rel="stylesheet" href="style.css">

@section('content')
<div class="container text-center">
        <div class="row align-items-start">
            <div class="col-5">
                <h1>Crear Producto</h1>
            </div>
        </div>
    <form action="{{ route('productos.store') }}" method="POST">
        @csrf

        <div class="col-1 col-sm-10">
                <div class="form-group">
                    <div class="col-1">
                        <br>
                         <label for="nombre">Nombre:</label>
                    </div>
                </div>
            <input type="text" name="nombre" class="form-control">
        </div>

        <div class="col-1 col-sm-10">
                <div class="form-group">
                    <div class="col-1">
                        <br>
                            <label for="detail">Detalle:</label>
                    </div>
                </div>
            <input type="text" name="detail" class="form-control">
        </div>

        <div class="col-1 col-sm-10">
                <div class="form-group">
                    <div class="col-1">
                        <br>
                            <label for="precio">Precio:</label>
                    </div>
                </div>
            <input type="number" name="precio" class="form-control">
        </div>

        <div class="col-1 col-sm-10">
                <div class="form-group">
                    <div class="col-1">
                        <br>
                            <label for="formFileSm" class="form-label">Imagen</label>
                        </div>
                    </div>              
                    <input class="form-control form-control-sm" id="formFileSm" type="file">
                </div>
            <div>

            <br>    

        <button type="submit" class="btn btn-primary">Guardar</button>

        <a href="{{ route('productos.index') }}" class="btn btn-primary">Volver</a>
    </form>
@endsection
@push('scripts')
    <script>
        @if(session('productoCreado'))
            window.location = '{{ route("productos.index") }}' + '#producto-{{ session("productoCreado")->id }}';
        @endif
    </script>
@endpush    

resources/views/productos/edit.blade.php
<!-- resources/views/productos/edit.blade.php -->
@extends('layouts.app')

@section('content')
<div class="container text-center">
        <div class="row align-items-start">
            <div class="col-5">
                <h1>Editar Producto</h1>
            </div>
        </div>
    <div class="col">
        <form action="{{ route('productos.update', $producto->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="col-0 col-sm-10">
                <div class="form-group">
                    <div class="col-1">
                        <br>
                        <label for="name">Nombre:</label>
                    </div>
                </div>
                <input type="text" name="name" class="form-control" value="{{ $producto->name }}">
            </div>
            
            <div class="col-1 col-sm-10">
                <div class="form-group">
                    <div class="col-1">
                        <br>
                        <label for="detail">Detalle:</label>
                    </div>
                </div>   
                <textarea name="detail" class="form-control">{{ $producto->detail }}</textarea>
            </div>

            <div class="col-8 col-sm-10">
                <div class="form-group">
                    <div class="col-1">
                        <br>
                        <label for="price">Precio:</label>
                    </div>
                </div>
                <input type="number" name="price" class="form-control" value="{{ $producto->price }}">
            </div>
            <br>

            <button type="submit" class="btn btn-primary">Actualizar</button>

            <a href="{{ route('productos.index') }}" class="btn btn-primary">Volver</a>

        </form>
    </div>
@endsection

resources/views/productos/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container text-center">
        <div class="row align-items-start">
            <div class="col-5">
            <h1>Lista de Productos</h1>

        </div>
            <div class="col">
                <a href="{{ route('productos.create') }}" class="btn btn-success">Crear Producto</a>
            </div>
            <div class="col">
        </div>
    </div>
    </div>
        <div class="container">
  <div class="row">
  <div class="col-md-11 offset-md-0">
    <table class="table mt-3">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Detalle</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($productos as $producto)
                <tr>
                    <td>{{ $producto->id }}</td>
                    <td>{{ $producto->nombre }}</td>
                    <td>{{ $producto->detalles }}</td>
                    <td>{{ $producto->precio }}</td>
                    <td>
                        <a href="{{ route('productos.show', $producto->id) }}" class="btn btn-primary">Ver</a>
                        <a href="{{ route('productos.edit', $producto->id) }}" class="btn btn-warning">Editar</a>
                        <form action="{{ route('productos.destroy', $producto->id) }}" method="POST" style="display: inline-block;">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro de eliminar este producto?')">Eliminar</button>
                        </form>
                    </td>
                </tr>
            </div>
            @endforeach
            </div>
        </div>
        </tbody>
    </table>

    </div>
@endsection
<!-- Delete Modal HTML -->
<div id="deleteEmployeeModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form>
                <div class="modal-header">						
                    <h4 class="modal-title">Delete Employee</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">					
                    <p>Are you sure you want to delete these Records?</p>
                    <p class="text-warning"><small>This action cannot be undone.</small></p>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>

resources/views/productos/show.blade.php
<!-- resources/views/productos/show.blade.php -->
@extends('layouts.app')

@section('content')
<div class="container text-center">
        <div class="row align-items-start">
            <div class="col-5">
                <h1>Detalles del Producto</h1>
            </div>
            <div class="container">
            <div class="row">
            <div class="col-md-3 offset-md-0">
            <table class="table mt-3">
                <p><strong>ID:</strong> {{ $producto->id }}</p>
                <p><strong>Nombre:</strong> {{ $producto->nombre }}</p>
                <p><strong>Detalle:</strong> {{ $producto->detail }}</p>
                <p><strong>Precio:</strong> {{ $producto->precio }}</p>

                <a href="{{ route('productos.index') }}" class="btn btn-primary">Volver</a>
                </table>
             </div>
    </div>
    
@endsection